version: '3.7'
services:
  core:
    image: acentera/prod:acentera-aws-core-0.0.4
    volumes:
      - /dev/shm:/dev/shm
      - ./go/:/lambda/
      - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file:
       - .env
    environment:
       JWT_SECRET: "docker-compose-secret"
       STACK_ID: "arn:aws:cloudformation:us-east-1:123456789012:stack/local/51af3dc0-da77-11e4-872e-1234567db123"
       SESSION_TABLE_NAME: "app-data-sessions"
       SMS_CONFIG_ARN: ""
       ADMIN_USERNAME: ${ADMIN_USERNAME}
       AWS_LAMBDA_FUNCTION_HANDLER: "main"
       EMAIL_ENABLED: "false"
       SMS_CONFIG_EXTERNAL_ID: ""
       KEY_ID: ${KEY_ID}
       AWS_ACCESS_KEY_ID: "a"
       APP_DATA_PERM_TABLE_NAME: "app-data-permissions"
       AWS_DEFAULT_REGION: "us-east-1"
       SKIP_SSM: "true"
       LOGINSRV_DYNAMODB: "endpoint=http://dynamodb:8000,table=app-data"
       SKIP_COGNITO: "true"
       STACK_NAME: "local"
       AWS_SAM_LOCAL: "true"
       AWS_REGION: "us-east-1"
       SECRET: ""
       AWS_SECRET_ACCESS_KEY: "a"
       APP_DATA_TABLE_NAME: "app-data"
       STAGE: ""
       RUNWS: "true"
#    ports:
#     - "127.0.0.1:3000:3000"
#       # old cmd #make dev
    command:
      /go/src/github.com/nzoschke/gofaas/handlers/app/main

    networks:
      traeffik:
      backend:
        aliases:
          - core

  core-vue:
    image: acentera/prod:acentera-aws-core-vuejs-0.0.5
    environment:
       HOST: 0.0.0.0
       PORT: 80
       SOCKPORT: 80
       SOCKHOST: http://cms.dev.acentera
       #cms.dev.acentera
       #SOCKPORT: 443
       HTTPS: "true"
       HTTPS: "true"
       PUBLIC: http://cms.dev.acentera
       DEV_ACCOUNTID: ${DEV_ACCOUNTID}
       ENV_CONFIG: ${ENV_CONFIG}
       BAD_API_HOST: 127.0.0.1
       FULL_BASE_API: https://apiproxy.dev.acentera/api/
       FULL_BASE_PLUGIN_URL: https://apiproxy.dev.acentera
       FULL_GRAPHQL_LOCAL_URL: https://graphql.dev.acentera
       SITE_TITLE: ${SITE_TITLE}
    networks:
      traeffik:
      backend:
        aliases:
          - core-vue

    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_cms.rule=Host(`cms.dev.acentera`)"
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_cms.entrypoints=http"
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_https_cms.rule=Host(`cms.dev.acentera`)"
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_https_cms.entrypoints=https"
     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_https_cms.tls=true"
     - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_https_cms.redirectscheme.scheme=https"
     - "traefik.http.services.${COMPOSE_PROJECT_NAME}_https_cms.loadbalancer.server.port=80"
     - "traefik.http.services.${COMPOSE_PROJECT_NAME}_https_cms.loadbalancer.server.scheme=https"

networks:
    backend:
      name: ${COMPOSE_PROJECT_NAME}_backend

    traeffik:
       external:
          name: acentera-backend
