
version: '3.7'
services:
  serverless-cms-vue:
    build:
      context: .
    volumes:
      - .:/usr/app/
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./backend/go/customvendors/static:/customvendors/static
    environment:
       HOST: 0.0.0.0
       PORT: 80
       DEV_ACCOUNTID: ${DEV_ACCOUNTID}
       ENV_CONFIG: ${ENV_CONFIG}
    networks:
      backend:
        aliases:
          - serverless-cms-vue
    ports:
      - "127.0.0.1:81:80"

  serverless-cms-graphql:
    build:
      context: .
      dockerfile: Dockerfile-graph
    volumes:
      - ./backend/appsync.local.js:/usr/app/appsync.local.js
      - ./backend/go/schema.graphql:/usr/app/schema.graphql
      - ./backend/go/template.yml:/usr/app/template.yml
    environment:
       LOCAL_LAMBDA_HOST: serverless-cms
       LOCAL_LAMBDA_PORT: 3001
    networks:
      backend:
        aliases:
          - serverless-cms-graphql
    ports:
      - "127.0.0.1:4000:4000"

  serverless-cms:
    build: 
       context: backend/go/.
    volumes:
      - ./backend/go/:/go/src/github.com/myplugin/gofaas
      - ./README.md:/go/src/github.com/myplugin/gofaas/README.md:ro
      - ./LICENSE:/go/src/github.com/myplugin/gofaas/LICENSE:ro
      - ./go/shared:${PWD}/backend/go/shared
      - ./backend/go/customvendors/static:/go/src/github.com/acenterastatic/static
      - /var/run/docker.sock:/var/run/docker.sock:rw
    # network_mode: bridge
    networks:
      backend:
        aliases:
          - serverless-cms
    env_file:
       - .env
    environment:
       PLUGINNAME: ${PLUGIN_NAME}
       PLUGIN_NAME: ${PLUGIN_NAME}
       PluginName: ${PLUGIN_NAME}
       SITE_KEY: ${PLUGIN_KEY}
       DOCKER_NETWORK: ${COMPOSE_PROJECT_NAME}_backend
       JWT_SECRET: "docker-compose-secret"
       STACK_ID: "arn:aws:cloudformation:us-east-1:123456789012:stack/local/51af3dc0-da77-11e4-872e-1234567db123"
       SESSION_TABLE_NAME: "app-data-sessions"
       SMS_CONFIG_ARN: ""
       ADMIN_USERNAME: ${ADMIN_USERNAME}
       AWS_LAMBDA_FUNCTION_HANDLER: "main"
       EMAIL_ENABLED: "false"
       SMS_CONFIG_EXTERNAL_ID: ""
       KEY_ID: ${KEY_ID}
       AWS_ACCESS_KEY_ID: "a"
       APP_DATA_PERM_TABLE_NAME: "app-data-permissions"
       AWS_DEFAULT_REGION: "us-east-1"
       SKIP_SSM: "true"
       LOGINSRV_DYNAMODB: "endpoint=http://dynamodb:8000,table=app-data"
       SKIP_COGNITO: "true"
       STACK_NAME: "local"
       AWS_SAM_LOCAL: "true"
       AWS_REGION: "us-east-1"
       SECRET: ""
       AWS_SECRET_ACCESS_KEY: "a"
       APP_DATA_TABLE_NAME: "app-data"
       STAGE: ""
       RUNWS: "true"
       HOME_PWD: ${PWD}/backend/go/
    ports:
      - "3003:3000"
      - "3001:3000"
    command: |
       make dev
       
networks:
    backend:
      name: ${COMPOSE_PROJECT_NAME}_backend
